INSERT INTO AUTHORITY VALUES('Insert Employee');
INSERT INTO AUTHORITY VALUES('Insert Doctor');
INSERT INTO AUTHORITY VALUES('Insert Customer');
INSERT INTO AUTHORITY VALUES('Insert Stock');
INSERT INTO AUTHORITY VALUES('Update Employee');
INSERT INTO AUTHORITY VALUES('Update Doctor');
INSERT INTO AUTHORITY VALUES('Update Customer');
INSERT INTO AUTHORITY VALUES('Update Stock');
INSERT INTO AUTHORITY VALUES('Delete Employee');
INSERT INTO AUTHORITY VALUES('Delete Doctor');
INSERT INTO AUTHORITY VALUES('Delete Customer');
INSERT INTO AUTHORITY VALUES('Delete Stock');
INSERT INTO AUTHORITY values('APPLOINTMENT');

INSERT INTO DEPARTMENT(name) values('a');
INSERT INTO DEPARTMENT(name) values('b');
INSERT INTO DEPARTMENT(name) values('c');

